name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install -y gcc make cmake git build-essential libc6-dev
        echo $(gcc --version)

    - name: make
      run: make CFLAGS="-static -O3 -s" LDFLAGS="-static" BUILD_SHARED=""

    - name: Verify static build
      run: |
        file lz4
        ldd lz4 || true
